services:
  db:
    image: postgres:16-alpine
    container_name: social_db
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: a9w6Vx3Mn2FEuyRY3voTrlhy5PSl9Smj
      POSTGRES_DB: social_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
      - DAC_OVERRIDE

  app:
    build: .
    container_name: social_app
    ports:
      - "127.0.0.1:3011:3011"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://social:@db:5432/social_db
    volumes:
      - ./uploads:/app/public/uploads
      - ./.next:/app/.next:ro
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 1G

volumes:
  pgdata:
    name: social_pgdata
